export const profileCatalog = {
  institutions: ['Duoc UC'],
  campuses: [
    'Campus Virtual',
    'Sede Alameda',
    'Sede Padre Alonso de Ovalle',
    'Sede Antonio Varas',
    'Sede Maipú',
    'Sede Melipilla',
    'Sede Plaza Norte',
    'Sede Plaza Oeste',
    'Sede Plaza Vespucio',
    'Sede Puente Alto',
    'Sede San Bernardo',
    'Sede San Carlos de Apoquindo',
    'Sede San Joaquín',
    'Sede Valparaíso',
    'Sede Viña del Mar',
    'Campus Arauco',
    'Campus Nacimiento',
    'Sede San Andrés de Concepción',
    'Campus Villarrica',
    'Sede Puerto Montt',
  ],
  careers: [
    'Administración de Empresas',
    'Administración en Turismo y Hospitalidad Mención Administración Hotelera',
    'Administración en Turismo y Hospitalidad Mención Gestión de Destinos Turísticos',
    'Administración en Turismo y Hospitalidad Mención Gestión para el Ecoturismo',
    'Administración en Turismo y Hospitalidad Mención Hospitality Management',
    'Administración Pública',
    'Analista Programador',
    'Analista Programador Computacional',
    'Animación Digital',
    'Auditoría',
    'Auditoría y Análisis de Negocios',
    'Comercio Exterior',
    'Comunicación Audiovisual',
    'Contabilidad General Mención Legislación Tributaria',
    'Contabilidad Tributaria',
    'Desarrollo de Aplicaciones',
    'Desarrollo y Diseño Web',
    'Dibujo y Modelamiento Arquitectónico y Estructural',
    'Diseño de Ambientes',
    'Diseño de Vestuario',
    'Diseño Gráfico',
    'Diseño Industrial e Innovación en Productos',
    'Gastronomía',
    'Gastronomía Internacional',
    'Ilustración para Contextos Globales',
    'Informática Biomédica',
    'Ingeniería Agrícola',
    'Ingeniería en Administración Mención Finanzas',
    'Ingeniería en Administración Mención Gestión de Personas',
    'Ingeniería en Administración Mención Innovación y Emprendimiento',
    'Ingeniería en Automatización y Control Industrial',
    'Ingeniería en Ciberseguridad',
    'Ingeniería en Ciencia de Datos',
    'Ingeniería en Comercio Exterior',
    'Ingeniería en Construcción',
    'Ingeniería en Desarrollo de Software',
    'Ingeniería en Electricidad y Automatización Industrial',
    'Ingeniería en Gestión de Personas',
    'Ingeniería en Gestión Logística',
    'Ingeniería en Informática',
    'Ingeniería en Infraestructura Tecnológica',
    'Ingeniería en Maquinaria y Vehículos Pesados',
    'Ingeniería en Mantenimiento Industrial',
    'Ingeniería en Marketing Digital',
    'Ingeniería en Mecánica Automotriz y Autotrónica',
    'Ingeniería en Medio Ambiente',
    'Ingeniería en Prevención de Riesgos',
    'Ingeniería en Redes y Telecomunicaciones',
    'Ingeniería en Sonido',
    'Ingeniería Industrial',
    'Preparador Físico',
    'Publicidad',
    'Relaciones Públicas y Comunicación Organizacional',
    'Restauración de Bienes Patrimoniales',
    'Técnico Agrícola',
    'Técnico Audiovisual',
    'Técnico de Redes y Telecomunicaciones',
    'Técnico en Administración',
    'Técnico en Calidad de Alimentos',
    'Técnico en Construcción',
    'Técnico en Control y Monitoreo Remoto de Procesos Mineros',
    'Técnico en Electricidad y Automatización Industrial',
    'Técnico en Electricidad y Energías Renovables',
    'Técnico en Enfermería',
    'Técnico en Geología',
    'Técnico en Gestión Logística',
    'Técnico en Laboratorio Clínico y Banco de Sangre',
    'Técnico en Mantenimiento Industrial',
    'Técnico en Maquinaria y Vehículos Pesados',
    'Técnico en Mecánica Automotriz y Autotrónica',
    'Técnico en Odontología',
    'Técnico en Operación y Supervisión de Procesos Mineros',
    'Técnico en Operaciones Logísticas',
    'Técnico en Prevención de Riesgos',
    'Técnico en Prevención de Riesgos Laborales',
    'Técnico en Química y Farmacia',
    'Técnico en Radiodiagnóstico y Radioterapia',
    'Técnico en Trabajo Social',
    'Técnico en Turismo y Hospitalidad',
    'Técnico Topógrafo Geomático',
    'Técnico Veterinario y Pecuario',
    'Tecnología en Sonido e Iluminación',
  ],
  verifiedAt: '2026-08-25',
  sources: {
    campuses: 'https://www.duoc.cl/nosotros/donde-estamos/sedes/',
    careers: 'https://www.duoc.cl/oferta-academica/',
  },
} as const

const normalize = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
    .toLocaleLowerCase('es-CL')

export function canonicalCatalogValue(
  value: string | null | undefined,
  options: readonly string[],
) {
  if (!value) return null
  const normalized = normalize(value)
  return options.find((option) => normalize(option) === normalized) ?? null
}
